<!DOCTYPE html>
<!-- saved from url=(0043)http://flatfull.com/themes/musik/index.html -->
<html lang="en" class="app js no-touch no-android chrome no-firefox no-iemobile no-ie no-ie8 no-ie10 no-ie11 no-ios no-ios7 ipad">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Musik | Web Application</title>
    <meta name="description" content="app, web app, responsive, admin dashboard, admin, flat, flat ui, ui kit, off screen nav">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="/css/jplayer.flat.css" type="text/css">

    <link rel="stylesheet" href="/css/app.v1.css" type="text/css">
    <link rel="stylesheet" href="/css/chosen.css" type="text/css">
    <link rel="stylesheet" href="/css/sweetalert.css" type="text/css">
    <script src="/js/axios.min.js"></script>
    <script type="text/javascript" src="/js/jquery-2.1.1.js"></script>
    <script type="text/javascript" src="/js/Bootstrap.min.js"></script>
    <script src="/js/plugins/chosen.jquery.js"></script>
    <script src="/js/jquery.jplayer.min.js"></script>
    <script src="/js/jplayer.playlist.min.js"></script>
    <script src="/js/plugins/sweetalert2.min.js"></script>

    <script type="text/javascript" src="/js/vue.js"></script>
    <script src="/js/vue-router.js"></script>
    <script src="/js/components/star-rating.min.js"></script>
    <script src="/js/components/Aplayer.min.js"></script>

    <?php $this->partial('index/index'); ?>
    <?php $this->partial('playlist/index'); ?>
    <?php $this->partial('playlist/info'); ?>
    <?php $this->partial('layouts/header'); ?>
    <?php $this->partial('layouts/left_menu'); ?>
    <!--[if lt IE 9]> <script src="js/ie/html5shiv.js"></script> <script src="js/ie/respond.min.js"></script> <script src="js/ie/excanvas.js"></script> <![endif]-->
  </head>

  <body>
    <section class="vbox" id="music-app">
      <music-header :songs="state.songs" v-model="menu"  ref="header"></music-header>
      <section>
        <section class="hbox stretch"> 
          <music-leftmenu v-model="menu" ref="menu"></music-leftmenu>
          <section id="content">
            <section class="hbox stretch">
              <section>
                <section class="vbox">
                  <router-view></router-view>
                  <footer class="footer bg-dark" v-if="player.available">
                    <a-player :audio="playlist" :lrcType="3" @remove="removeClick" @playing="setSong" v-on:cct="saveCount" v-on:cpl="clearList" ref="player"/>
                  </footer>
                </section>
              </section> <!-- side content -->
              
            </section> 
          </section>
        </section>
      </section>
    </section> 
    <!-- Bootstrap -->
    <!-- App -->
    
    <script type="text/javascript" src="/js/demo.js"></script>
  </body>
</html>
      