<header class="bg-white-only header header-md navbar navbar-fixed-top-xs" id="header_top">
  <div class="navbar-header aside bg-info " v-bind:class="{'nav-xs': menu_close}"> 
    <a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen,open" data-target="#nav,html"> 
      <i class="icon-list"></i> 
    </a> 
    <a href="#" class="navbar-brand text-lt"> 
      <i class="icon-earphones"></i> 
      <img src="/img/logo.png" alt="." class="hide"> <span class="hidden-nav-xs m-l-sm">Musik</span> 
    </a> 
    <a class="btn btn-link visible-xs" data-toggle="dropdown" data-target=".user"> <i class="icon-settings"></i> </a> 
  </div>
  <ul class="nav navbar-nav hidden-xs">
    <li> 
      <a href="#nav,.navbar-header" v-on:click.stop.prevent="menuexpand" class="text-muted"> 
        <i class="fa fa-indent text"></i> <i class="fa fa-dedent text-active"></i> 
      </a> 
    </li>
  </ul>
  <form class="navbar-form navbar-left m-t m-l-n-xs hidden-xs" role="search">
    <div class="form-group">
      <div class="input-group" v-bind:class="{'open':query!=''}"> 
        <input type="text" class="form-control input-sm no-border rounded" placeholder="Search songs, albums, tags..." style="width: 200px;" v-model="query" v-on:keyup.escape="query=''">
        <section class="dropdown-menu aside-xl animated fadeInUp" style="max-height: 500px;overflow-y: auto;">
          <section class="panel bg-white">
            <div class="list-group list-group-alt">
              <div href="#" class="media list-group-item" v-for="s in songsQuery"> 
                <span class="media-body block m-b-none"> 
                  <span class="pull-right m-t-xs">
                    <a href="#" v-on:click.stop.prevent="playSong(s)">
                      <i class="fa fa-play-circle fa-2x text-muted" v-if="!s.playing" ></i>
                      <i class="fa fa-pause fa-2x text-muted" v-if="s.playing" ></i>
                    </a>
                  </span>
                  <div>
                    <a v-bind:href="'/songs/'+s.id" class="text-ellipsis">
                      {{s.filename}}<br/>
                      <small class="text-muted">
                        {{s.tags.band}}
                      </small> 
                    </a>
                  </div>
                </span> 
              </div> 
            </div>
          </section>
        </section>
      </div>
    </div>
  </form>
  <div class="navbar-right">
    <ul class="nav navbar-nav m-n hidden-xs nav-user user">
      <li>
        <a href="#"> 
          <i class="fa fa-battery" v-bind:class="{'fa-battery-0 text-danger': (store.state.battery.level>=0&&store.state.battery.level<=0.20),'fa-battery-1': store.state.battery.level>0.20&&store.state.battery.level<=0.40,'fa-battery-2':store.state.battery.level>0.40&&store.state.battery.level<=0.60,'fa-battery-3':store.state.battery.level>0.60&&store.state.battery.level<=0.8, 'fa-battery-full': store.state.battery.level>=0.81}" v-bind:title="Math.round(store.state.battery.level * 100) + '%'"></i> 
          <i class="" v-bind:class="{'icon-energy': store.state.battery.charging, 'hide': !store.state.battery.charging}"></i> 
          <span class="small" v-bind:class="{'hide': store.state.battery.charging}">{{Math.round(store.state.battery.level * 100)}} %</span>
          <span class="badge badge-sm up bg-danger count hide" style="display: inline-block;"></span> 
        </a>
      </li>
      <li class="hidden-xs hide" v-bind:class="{'open': notification_is_open}"> 
        <a href="#" class="dropdown-toggle lt" data-toggle="dropdown" v-on:click.stop.prevent="showNotifications"> 
          <i class="icon-bell"></i> 
          <span class="badge badge-sm up bg-danger count" style="display: inline-block;">3</span> 
        </a>
        <section class="dropdown-menu aside-xl animated fadeInUp">
          <section class="panel bg-white">
            <div class="panel-heading b-light bg-light"> 
              <strong>You have <span class="count" style="display: inline;">3</span> notifications</strong> 
            </div>
            <div class="list-group list-group-alt">
              <a href="#" class="media list-group-item" style="display: block;">
                <span class="pull-left thumb-sm text-center">
                  <i class="fa fa-envelope-o fa-2x text-success"></i>
                </span>
                <span class="media-body block m-b-none">
                  Sophi sent you a email<br><small class="text-muted">1 minutes ago</small>
                </span>
              </a> 
              <a href="#" class="media list-group-item"> 
                <span class="pull-left thumb-sm"> 
                  <img src="/img/a0.png" alt="..." class="img-circle"> 
                </span> 
                <span class="media-body block m-b-none"> Use awesome animate.css<br> <small class="text-muted">10 minutes ago</small> </span> 
              </a> 
              <a href="#" class="media list-group-item"> 
                <span class="media-body block m-b-none"> 1.0 initial released<br> <small class="text-muted">1 hour ago</small> </span> 
              </a> 
            </div>
            <div class="panel-footer text-sm"> 
              <a href="#" class="pull-right">
                <i class="fa fa-cog"></i>
              </a> 
              <a href="#notes" data-toggle="class:show animated fadeInRight">See all the notifications</a> 
            </div>
          </section>
        </section>
      </li>
      <li class="dropdown hide" v-bind:class="{'open': profile_is_open}"> 
        <a href="#" class="dropdown-toggle bg clear" data-toggle="dropdown" v-on:click.stop.prevent="showProfile"> 
          <span class="thumb-sm avatar pull-right m-t-n-sm m-b-n-sm m-l-sm"> <img src="/img/a0.png" alt="..."> </span> 
          John.Smith <b class="caret"></b> 
        </a>
        <ul class="dropdown-menu animated fadeInRight">
          <li> <span class="arrow top"></span> <a href="#">Settings</a> </li>
          <li> <a href="/profile.html">Profile</a> </li>
          <li> <a href="/index.html#"> <span class="badge bg-danger pull-right">3</span> Notifications </a> </li>
          <li> <a href="/docs.html">Help</a> </li>
          <li class="divider"></li>
          <li> <a href="/modal.lockme.html" data-toggle="ajaxModal">Logout</a> </li>
        </ul>
      </li>
    </ul>
  </div>
</header>
<script type="text/javascript">
  var headerVue = new Vue({
    mixins: [mixin],
    el: "#header_top",
    data: {
      menu_close: true,
      notification_is_open: false,
      profile_is_open: false,
      query: "",
    },
    computed: {
      songsQuery: function() {
        var that = this;
        return this.state.songs.slice(0).filter((is)=> {
          return (
            that.clearFilter(that.query) !== '' && ( 
              that.clearFilter(Object.values(is).join('')).indexOf(that.clearFilter(that.query)) > -1 ||
              that.clearFilter(Object.values(is.tags).join('')).indexOf(that.clearFilter(that.query)) >- 1
            )
          );
        });
      },
    },
    methods: {
      menuexpand: function() {
        this.menu_close = leftMenuVue.menu_close = !this.menu_close;
      },
      showNotifications: function() {
        this.notification_is_open = !this.notification_is_open;
      },
      showProfile: function() {
        this.profile_is_open = !this.profile_is_open;
      },
    },
    mounted: function () {
      
    }
  });
</script>